	<div id="sidebar">
	<?php if ( !function_exists('dynamic_sidebar')|| !dynamic_sidebar('Sidebar') ) : ?>

        <div class="post s_header" style="border:0;">
<h3><img src="<?php bloginfo('stylesheet_directory'); ?>/images/tb4.gif" /><?php _e('最新评论') ?></h3> 
<!-- START of script generated by WP-RecentComments --> 
<link rel="stylesheet" href="/wp-content/plugins/wp-recentcomments/css/wp-recentcomments.css" type="text/css" media="screen" /> 
<script type="text/javascript" src="/wp-content/plugins/wp-recentcomments/js/wp-recentcomments.js"></script> 
<!-- END of script generated by WP-RecentComments --> 
<ul id="index_recent_comments"><?php wp_recentcomments(); ?></ul>

<!-- End Recent Comments -->
 </div>

 <div class="block">
      
			<?php wp_cumulus_insert(); ?> 
         <!-- <div class="s_line"></div>-->
		</div>
        
        
        
        

        
        
        <div class="block">
        <h3><img src="<?php bloginfo('stylesheet_directory'); ?>/images/tb5.gif" />热评文章</h3>
              <ul class="hotlist">
<?php get_mostcommented($limit=10); ?>
</ul>
        </div>
        
    
   <!--     <div class="block newslist">
			<h3>最新文章</h3>
				<?php //query_posts('showposts=5'); ?>
				<ul>
					<?php //while (have_posts()) : the_post(); ?>
					<li><a href="<?php //the_permalink() ?>"><?php //the_title(); ?></a></li>
					<?php //endwhile;?>
				</ul>
		</div>-->
        
  <!--      <div class="block">
         <div class="s_line" style="margin-top:10px;"></div>
        <a style="display:block; padding:10px 0;" href="http://www.wopus.org/" target="_blank"><img src="/gg/wopus.gif" /></a>
  
        </div>-->

	<div class="block">
     <h3><img src="<?php bloginfo('stylesheet_directory'); ?>/images/tb6.gif" />赞助商</h3>
    
    <script type="text/javascript"><!--
google_ad_client = "pub-8884570557731258";
/* 分页右250x250, 创建于 09-5-27 */
google_ad_slot = "1118350161";
google_ad_width = 250;
google_ad_height = 250;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
	    </div>	

		
	<?php endif; ?>
	</div>